### ISSUE TITLE
Goroutine leak in TxPool.cleaner

### ISSUE THREAD

**Issue by asubiotto** [polarsignals/frostdb#180]
I recently came across a weird failure mode where the race detector exceeded a threshold of allowed goroutines. I tracked this down to goroutines created in `TxPool.cleaner`:
```
--- FAIL: Test_Table_Concurrency (10.32s)
    leaks.go:78: found unexpected goroutines:
        [Goroutine 52 in state select, with github.com/polarsignals/frostdb.(*TxPool).cleaner on top of the stack:
        goroutine 52 [select]:
        github.com/polarsignals/frostdb.(*TxPool).cleaner(0x140003ed840, 0x140003ed730?)
        	/Users/asubiotto/Developer/github.com/polarsignals/frostdb/tx_list.go:79 +0xa0
        created by github.com/polarsignals/frostdb.NewTxPool
        	/Users/asubiotto/Developer/github.com/polarsignals/frostdb/tx_list.go:26 +0xe8
```

To reproduce, simply run `go test -run Test_Table_Concurrency` with a leak detector:

```
diff --git a/table_test.go b/table_test.go
index e74a689..a430e5f 100644
--- a/table_test.go
+++ b/table_test.go
@@ -24,6 +24,7 @@ import (
        "github.com/thanos-io/objstore/providers/filesystem"
        "go.opentelemetry.io/otel/trace"
        "go.uber.org/atomic"
+       "go.uber.org/goleak"

        "github.com/polarsignals/frostdb/dynparquet"
        schemapb "github.com/polarsignals/frostdb/gen/proto/go/frostdb/schema/v1alpha1"
@@ -490,6 +491,8 @@ func Test_Table_InsertLowest(t *testing.T) {

 // This test issues concurrent writes to the database, and expects all of them to be recorded successfully.
 func Test_Table_Concurrency(t *testing.T) {
+       defer goleak.VerifyNone(t)
+
        tests := map[string]struct {
                granuleSize int
        }{
```

I couldn't find an obvious `Close` method that was missing, so decided to record this in an issue. cc @thorfour

**Comment by asubiotto** [comment]
To be clear, this is a leak on current `main`. I'm also running into another leak in `asyncPage.init` and still need to investigate if we're not managing the page lifecycle properly. However, we should probably fix this leak first.
