### ISSUE TITLE
panic

### ISSUE THREAD

**Issue by thorfour** [polarsignals/frostdb#188]
```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x103359f08]

goroutine 25938 [running]:
github.com/polarsignals/frostdb.(*Granule).ColumnChunks(0x140258aaea0)
	/Users/thor/go/src/github.com/polarsignals/frostdb/granule.go:378 +0x338
github.com/polarsignals/frostdb.(*ColumnRef).Column(0x1404e80bf30, {0x106cbed48, 0x140258aaea0})
	/Users/thor/go/src/github.com/polarsignals/frostdb/binaryscalarexpr.go:108 +0x78
github.com/polarsignals/frostdb.BinaryScalarExpr.Eval({0x1404e80bf30, 0x1, {0x1401b743738, 0x6, 0xf9, 0x0, 0x0, 0x0}}, {0x106cbed48?, 0x140258aaea0?})
	/Users/thor/go/src/github.com/polarsignals/frostdb/binaryscalarexpr.go:130 +0x54
github.com/polarsignals/frostdb.(*AndExpr).Eval(0x1404dd991e0, {0x106cbed48, 0x140258aaea0})
	/Users/thor/go/src/github.com/polarsignals/frostdb/filter.go:132 +0x3c
github.com/polarsignals/frostdb.(*TableBlock).RowGroupIterator.func1({0x106cb0fe0?, 0x140258aaea0})
	/Users/thor/go/src/github.com/polarsignals/frostdb/table.go:935 +0x70
github.com/google/btree.(*node[...]).iterate(0x1404f4a3600, 0x1, {{0x0, 0x0?}, 0xb8?}, {{0x0?, 0x0?}, 0xa8?}, 0x0?, 0x0, ...)
	/Users/thor/go/pkg/mod/github.com/google/btree@v1.1.2/btree_generic.go:522 +0x318
github.com/google/btree.(*node[...]).iterate(0x1404f4a3240, 0x1, {{0x0, 0x0?}, 0x8?}, {{0x0?, 0x0?}, 0x18?}, 0x0?, 0x0, ...)
	/Users/thor/go/pkg/mod/github.com/google/btree@v1.1.2/btree_generic.go:510 +0x1a4
github.com/google/btree.(*node[...]).iterate(0x1404f4a31c0, 0x1, {{0x0, 0x0?}, 0x20?}, {{0x0?, 0x0?}, 0x0?}, 0x0?, 0x0, ...)
	/Users/thor/go/pkg/mod/github.com/google/btree@v1.1.2/btree_generic.go:510 +0x1a4
github.com/google/btree.(*node[...]).iterate(0x1404f4a3180, 0x1, {{0x0, 0x0?}, 0x68?}, {{0x0?, 0x0?}, 0x1?}, 0x0?, 0x0, ...)
	/Users/thor/go/pkg/mod/github.com/google/btree@v1.1.2/btree_generic.go:510 +0x1a4
github.com/google/btree.(*BTreeG[...]).Ascend(0x0?, 0x0?)
	/Users/thor/go/pkg/mod/github.com/google/btree@v1.1.2/btree_generic.go:779 +0x54
github.com/google/btree.(*BTree).Ascend(...)
	/Users/thor/go/pkg/mod/github.com/google/btree@v1.1.2/btree_generic.go:1029
github.com/polarsignals/frostdb.(*TableBlock).RowGroupIterator(0x140002bc240?, {0x1404a34b620?, 0x1404a34bce0?}, 0x10505edae?, {0x106cb0f60?, 0x1404dd991e0?}, 0x1400855a028?)
	/Users/thor/go/src/github.com/polarsignals/frostdb/table.go:931 +0x6c
github.com/polarsignals/frostdb.(*Table).collectRowGroups(0x140002bc240, {0x106cd4cb0?, 0x1404a34bce0?}, 0x10504e457?, {0x106cdc148, 0x1404a34b620})
	/Users/thor/go/src/github.com/polarsignals/frostdb/table.go:1317 +0x204
```

Hit this after running for a couple hours

**Comment by thorfour** [comment]
this code has been removed
