### ISSUE TITLE
wal: improve durability

### ISSUE THREAD

**Issue by asubiotto** [polarsignals/frostdb#311]
This issue tracks a couple of improvements to our handling of the write ahead log uncovered while running frostdb in production.

- [ ] Initialize in-memory state to on-disk state.
The WAL package that we use uses an index for each entry written to the WAL. The writer provides this index when writing to the WAL (https://github.com/tidwall/wal/blob/master/wal.go#L310). The WAL records the "last" index it has seen and the next write's index *must* be `lastIndex + 1`, otherwise the write is rejected. In frostdb, we conveniently use the txn id as the WAL index for each WAL entry https://github.com/polarsignals/frostdb/blob/e386dd63002bbb0eaf74999ff5f6ce8baabbc3fb/wal/wal.go#L193
When restarting an in-memory frostdb instance, the transaction ID is reset to 1 (since we have no on-disk state). This presents an issue when writing to the WAL because all writes to the WAL will be rejected as out-of-order (something we're observing) since the transaction id will be less than the `lastIndex` in the WAL (it is read from the lastest entry in WAL files). The proposal is to initialize the transaction high watermark to the on-disk WAL index. This can be obtained by first opening the wal and calling `LastIndex` https://github.com/tidwall/wal/blob/0fa32977a196086591e6eace7bdf13f67bc305aa/wal.go#L504.

- [ ] Truncate torn writes to avoid WAL corruption.
We have also observed `log corrupt` errors when reopening a WAL. After further analysis, this is caused by the fact that only half an entry has been persisted to disk (even when calling fsync). Concretely, WAL entries are written as `<size of entry><entry>` and we encounter an entry with a size larger than the following bytes. I don't think there is a mechanism in our WAL library that allows us to truncate corrupt entries and in any case we can't open a corrupt WAL to perform operations on it. Here, we probably have to write some custom WAL file reading to read the last file in the WAL (since corrupt entries should always be the last entries) and truncate after the penultimate entry (by reading the file and interpreting the size of each entry).

**Comment by brancz** [comment]
Regarding the first point, since we use the transaction, why does this happen even though after replaying we set the "correct" next transaction ID? https://github.com/polarsignals/frostdb/blob/e386dd63002bbb0eaf74999ff5f6ce8baabbc3fb/wal/wal.go#L301

**Comment by brancz** [comment]
Regarding the second point, I think we could even start with deleting/skipping the last file and do what you suggested as a follow up.

**Comment by metalmatze** [comment]
You're right. The replayWAL works as expected for Parca and FrostDB. 
At the end of this the `tx` and `highWatermark` are set correctly.
https://github.com/polarsignals/frostdb/blob/e386dd63002bbb0eaf74999ff5f6ce8baabbc3fb/db.go#L532-L533

We need to check if this is true for other setups we have.

**Comment by asubiotto** [comment]
That seems correct when replaying the WAL, but do we replay the WAL when restarting FrostDB? I don't see a call in `frostdb` nor `polarsignals`

**Comment by metalmatze** [comment]
I'll be looking at the `frostdb` and `polarsignals` combination. Parca itself seems to be just fine.

**Comment by metalmatze** [comment]
Seeing this now:
```
level=error db=profiling-9a891ff0-432f-4297-a49e-0811d265a743 name=storage ts=2023-01-25T09:32:01.761622131Z caller=wal.go:236 msg="failed to write WAL batch" err="out of order" batch="unsupported value type" lastIndex=38186 lastIndexErr=null
level=error db=profiling-9a891ff0-432f-4297-a49e-0811d265a743 name=storage ts=2023-01-25T09:32:03.496448779Z caller=wal.go:236 msg="failed to write WAL batch" err="out of order" batch="unsupported value type" lastIndex=38186 lastIndexErr=null
level=error db=profiling-9a891ff0-432f-4297-a49e-0811d265a743 name=storage ts=2023-01-25T09:32:03.496520809Z caller=wal.go:236 msg="failed to write WAL batch" err="out of order" batch="unsupported value type" lastIndex=38186 lastIndexErr=null
level=error db=profiling-9a891ff0-432f-4297-a49e-0811d265a743 name=storage ts=2023-01-25T09:32:05.408049909Z caller=wal.go:236 msg="failed to write WAL batch" err="out of order" batch="unsupported value type" lastIndex=38186 lastIndexErr=null
level=error db=profiling-d563e435-bdb4-434c-90d5-b4069fc7b8b0 name=storage ts=2023-01-25T09:32:08.168385294Z caller=wal.go:236 msg="failed to write WAL batch" err="out of order" batch="unsupported value type" lastIndex=30190 lastIndexErr=null
level=error db=profiling-d563e435-bdb4-434c-90d5-b4069fc7b8b0 name=storage ts=2023-01-25T09:32:08.565091275Z caller=wal.go:236 msg="failed to write WAL batch" err="out of order" batch="unsupported value type" lastIndex=30190 lastIndexErr=null
level=error db=profiling-9a891ff0-432f-4297-a49e-0811d265a743 name=storage ts=2023-01-25T09:32:10.447730478Z caller=wal.go:236 msg="failed to write WAL batch" err="out of order" batch="unsupported value type" lastIndex=38186 lastIndexErr=null
level=error db=profiling-d563e435-bdb4-434c-90d5-b4069fc7b8b0 name=storage ts=2023-01-25T09:32:16.232816002Z caller=wal.go:236 msg="failed to write WAL batch" err="out of order" batch="unsupported value type" lastIndex=30190 lastIndexErr=null
level=error db=profiling-d563e435-bdb4-434c-90d5-b4069fc7b8b0 name=storage ts=2023-01-25T09:32:16.232945002Z caller=wal.go:236 msg="failed to write WAL batch" err="out of order" batch="unsupported value type" lastIndex=30190 lastIndexErr=null
level=error db=profiling-d563e435-bdb4-434c-90d5-b4069fc7b8b0 name=storage ts=2023-01-25T09:32:17.134212962Z caller=wal.go:236 msg="failed to write WAL batch" err="out of order" batch="unsupported value type" lastIndex=30190 lastIndexErr=null
level=error db=profiling-d563e435-bdb4-434c-90d5-b4069fc7b8b0 name=storage ts=2023-01-25T09:32:17.265047649Z caller=wal.go:236 msg="failed to write WAL batch" err="out of order" batch="unsupported value type" lastIndex=30190 lastIndexErr=null
level=error db=profiling-d563e435-bdb4-434c-90d5-b4069fc7b8b0 name=storage ts=2023-01-25T09:32:18.545483332Z caller=wal.go:236 msg="failed to write WAL batch" err="out of order" batch="unsupported value type" lastIndex=30190 lastIndexErr=null
level=error db=profiling-d563e435-bdb4-434c-90d5-b4069fc7b8b0 name=storage ts=2023-01-25T09:32:19.637241734Z caller=wal.go:236 msg="failed to write WAL batch" err="out of order" batch="unsupported value type" lastIndex=30190 lastIndexErr=null
level=error db=profiling-d563e435-bdb4-434c-90d5-b4069fc7b8b0 name=storage ts=2023-01-25T09:32:26.923356009Z caller=wal.go:236 msg="failed to write WAL batch" err="out of order" batch="unsupported value type" lastIndex=30190 lastIndexErr=null
level=error db=profiling-d563e435-bdb4-434c-90d5-b4069fc7b8b0 name=storage ts=2023-01-25T09:32:34.025929792Z caller=wal.go:236 msg="failed to write WAL batch" err="out of order" batch="unsupported value type" lastIndex=30190 lastIndexErr=null
level=error db=profiling-d563e435-bdb4-434c-90d5-b4069fc7b8b0 name=storage ts=2023-01-25T09:32:47.436775128Z caller=wal.go:236 msg="failed to write WAL batch" err="out of order" batch="unsupported value type" lastIndex=30190 lastIndexErr=null
level=error db=profiling-d563e435-bdb4-434c-90d5-b4069fc7b8b0 name=storage ts=2023-01-25T09:32:47.437224038Z caller=wal.go:236 msg="failed to write WAL batch" err="out of order" batch="unsupported value type" lastIndex=30190 lastIndexErr=null
level=error db=profiling-d563e435-bdb4-434c-90d5-b4069fc7b8b0 name=storage ts=2023-01-25T09:33:09.952168288Z caller=wal.go:236 msg="failed to write WAL batch" err="out of order" batch="unsupported value type" lastIndex=30190 lastIndexErr=null
level=error db=profiling-d563e435-bdb4-434c-90d5-b4069fc7b8b0 name=storage ts=2023-01-25T09:33:28.876619065Z caller=wal.go:265 msg="failed to truncate WAL" tx=3 err="out of range"
```

**Comment by metalmatze** [comment]
Even with the work in #313 we still have some panics when replaying: 
```
panic: runtime error: index out of range [1081] with length 1081

goroutine 118 [running]:
github.com/tidwall/wal.(*Log).Read(0xc0000b6500, 0xcd7)
	github.com/tidwall/wal@v1.1.7/wal.go:635 +0x625
github.com/polarsignals/frostdb/wal.(*FileWAL).Replay(0xc00025ac40, 0xc001149c50)
	github.com/polarsignals/frostdb@v0.0.0-20230125055640-ee8d238813f6/wal/wal.go:328 +0x405
github.com/polarsignals/frostdb.(*DB).replayWAL(0xc000170c00, {0x31d4560?, 0xc000509e40})
	github.com/polarsignals/frostdb@v0.0.0-20230125055640-ee8d238813f6/db.go:392 +0x8a
github.com/polarsignals/frostdb.(*ColumnStore).ReplayWALs.func1()
	github.com/polarsignals/frostdb@v0.0.0-20230125055640-ee8d238813f6/db.go:249 +0x66
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
```

**Comment by asubiotto** [comment]
Very weird. Have you been able to reproduce in a unit test? I wonder if we're replaying the WAL while something else is using the WAL. In any case, I think these issues belong in a new issue each.

Interestingly, in the "out of order" error case, it looks like the last index jumps from `38186` to `30190` then back again, which might be a clue as to what's going on.

**Comment by asubiotto** [comment]
Closing this given the original outlined work has been completed, tracking the panic in our cloud repo since I don't think this is an issue with FrostDB
