### ISSUE TITLE
arrow ingestion panic

### ISSUE THREAD

**Issue by brancz** [polarsignals/frostdb#368]
We've been test-running Parca with arrow ingestion enabled and ran into this panic. It might be unrelated but I believe we haven't seen this before:

```
panic: programming error; unable to find granule for part

goroutine 75 [running]:
github.com/polarsignals/frostdb.addPartToGranule({0xc0566cefc0, 0x1, 0xf520c5?}, 0xc0544cd040?)
        github.com/polarsignals/frostdb@v0.0.0-20230227172736-d0eea82a3fcb/table.go:1324 +0x12b
github.com/polarsignals/frostdb.(*TableBlock).compactGranule.func2(0xc008fbda28?)
        github.com/polarsignals/frostdb@v0.0.0-20230227172736-d0eea82a3fcb/compaction.go:455 +0x34
github.com/polarsignals/frostdb/parts.(*List).Iterate(0xc0459e9dc0, 0xc08b49fb60)
        github.com/polarsignals/frostdb@v0.0.0-20230227172736-d0eea82a3fcb/parts/part_list.go:90 +0x5f
github.com/polarsignals/frostdb.(*TableBlock).compactGranule(0xc000467180, 0xc0095e8280, 0xc0001a8078)
        github.com/polarsignals/frostdb@v0.0.0-20230227172736-d0eea82a3fcb/compaction.go:454 +0x83c
github.com/polarsignals/frostdb.(*TableBlock).compact.func1({0x51e9340?, 0xc0095e8280})
        github.com/polarsignals/frostdb@v0.0.0-20230227172736-d0eea82a3fcb/compaction.go:150 +0x125
github.com/google/btree.(*node[...]).iterate(0x52582a0, 0x2, {{0x0?, 0x0?}, 0x0?}, {{0x0?, 0x0?}, 0x0?}, 0x0, 0x1, ...)
        github.com/google/btree@v1.1.2/btree_generic.go:522 +0x3f7
github.com/google/btree.(*node[...]).iterate(0x52582a0, 0xc032960940, {{0x0?, 0x0?}, 0x7?}, {{0x0?, 0x0?}, 0x1?}, 0x0, 0x0, ...)
        github.com/google/btree@v1.1.2/btree_generic.go:527 +0x4be
github.com/google/btree.(*BTreeG[...]).Ascend(0xc000467180?, 0xfc05a0?)
        github.com/google/btree@v1.1.2/btree_generic.go:779 +0x49
github.com/google/btree.(*BTree).Ascend(...)
        github.com/google/btree@v1.1.2/btree_generic.go:1029
github.com/polarsignals/frostdb.(*TableBlock).compact(0xc000467180, 0xc0001a8078)
        github.com/polarsignals/frostdb@v0.0.0-20230227172736-d0eea82a3fcb/compaction.go:138 +0xc7
github.com/polarsignals/frostdb.(*compactorPool).compactLoop(0xc0013a1dd0, {0x5216018, 0xc000420140})
        github.com/polarsignals/frostdb@v0.0.0-20230227172736-d0eea82a3fcb/compaction.go:127 +0x2ed
github.com/polarsignals/frostdb.(*compactorPool).start.func1()
        github.com/polarsignals/frostdb@v0.0.0-20230227172736-d0eea82a3fcb/compaction.go:99 +0x66
created by github.com/polarsignals/frostdb.(*compactorPool).start
        github.com/polarsignals/frostdb@v0.0.0-20230227172736-d0eea82a3fcb/compaction.go:97 +0x6d
```

**Comment by asubiotto** [comment]
This was previously an ordering issue. We fixed this for parquet ingestion and now have an `unsorted_inserts_total` metric but the equivalent is unfortunately not implemented for the arrow ingestion path. I would bet that the arrow records are not sorted as expected.

**Comment by thorfour** [comment]
The `SeriesToArrowRecord` function definitely doesn't sort the row like the normal path does, so it's definitely that.

**Comment by thorfour** [comment]
Above PR seems to have fixed this panic, though we should still add the sorting guardrail.

**Comment by metalmatze** [comment]
Seeing this panic when updating to the latest FrostDB in Epimetheus too. 
It works in `bb0c4c0b` but doesn't in `74bb058c`
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x101629ec8]

goroutine 195 [running]:
github.com/apache/arrow/go/v10/arrow/array.(*String).Value(...)
        /Users/metalmatze/pkg/mod/github.com/apache/arrow/go/v10@v10.0.1/arrow/array/string.go:53
github.com/polarsignals/frostdb/pqarrow.appendToRow({0x1402070db00, 0x15, 0x2b}, {0x1041abbf0?, 0x1400111aff0?}, 0x645b?, 0x0?, 0x1?, 0x19?)
        /Users/metalmatze/pkg/mod/github.com/polarsignals/frostdb@v0.0.0-20230309224239-74bb058c1c64/pqarrow/parquet.go:48 +0x4b8
github.com/polarsignals/frostdb/pqarrow.getRecordRow(0x1420461dc20?, 0x140001a8930?, {0x1041a92e8, 0x14001539950}, 0x3?, {0x14005f00000, 0x2b, 0x2?}, {0x140015c3000, 0x2b, ...})
        /Users/metalmatze/pkg/mod/github.com/polarsignals/frostdb@v0.0.0-20230309224239-74bb058c1c64/pqarrow/parquet.go:85 +0x10c
github.com/polarsignals/frostdb/pqarrow.RecordToFile(0x140001a89a0, 0x1400089d560, {0x1041a92e8, 0x14001539950})
        /Users/metalmatze/pkg/mod/github.com/polarsignals/frostdb@v0.0.0-20230309224239-74bb058c1c64/pqarrow/parquet.go:174 +0x244
github.com/polarsignals/frostdb/parts.(*Part).SerializeBuffer(0x140001a89a0?, 0x1041677c0?, 0x1420461c960?)
        /Users/metalmatze/pkg/mod/github.com/polarsignals/frostdb@v0.0.0-20230309224239-74bb058c1c64/parts/part.go:50 +0x34
github.com/polarsignals/frostdb/parts.(*Part).AsSerializedBuffer(0x14001386c00, 0x140001a89a0)
        /Users/metalmatze/pkg/mod/github.com/polarsignals/frostdb@v0.0.0-20230309224239-74bb058c1c64/parts/part.go:66 +0xbc
github.com/polarsignals/frostdb.compactLevel0IntoLevel1(0x1400020a300, 0x1?, {0x14001646418, 0x1, 0x1}, {0x0, 0x0, 0x0?}, 0x3ff0000000000000, 0x14007a6fb48)
        /Users/metalmatze/pkg/mod/github.com/polarsignals/frostdb@v0.0.0-20230309224239-74bb058c1c64/compaction.go:565 +0x2e8
github.com/polarsignals/frostdb.(*TableBlock).Serialize.func2({0x10416cc60?, 0x14001386c40?})
        /Users/metalmatze/pkg/mod/github.com/polarsignals/frostdb@v0.0.0-20230309224239-74bb058c1c64/table.go:1443 +0x13c
github.com/google/btree.(*node[...]).iterate(0x1041c48a0, 0x50, {{0x0?, 0x0?}, 0x0?}, {{0x0?, 0x0?}, 0x48?}, 0x0?, 0x0, ...)
        /Users/metalmatze/pkg/mod/github.com/google/btree@v1.1.2/btree_generic.go:522 +0x314
github.com/google/btree.(*BTreeG[...]).Ascend(0x140001a8930?, 0x1400020a280?)
        /Users/metalmatze/pkg/mod/github.com/google/btree@v1.1.2/btree_generic.go:779 +0x50
github.com/google/btree.(*BTree).Ascend(...)
        /Users/metalmatze/pkg/mod/github.com/google/btree@v1.1.2/btree_generic.go:1029
github.com/polarsignals/frostdb.(*TableBlock).Serialize(0x1400020a300, {0x10416fb80, 0x14001584038})
        /Users/metalmatze/pkg/mod/github.com/polarsignals/frostdb@v0.0.0-20230309224239-74bb058c1c64/table.go:1431 +0x3d0
github.com/polarsignals/frostdb.(*TableBlock).Persist.func1()
        /Users/metalmatze/pkg/mod/github.com/polarsignals/frostdb@v0.0.0-20230309224239-74bb058c1c64/store.go:29 +0x60
created by github.com/polarsignals/frostdb.(*TableBlock).Persist
        /Users/metalmatze/pkg/mod/github.com/polarsignals/frostdb@v0.0.0-20230309224239-74bb058c1c64/store.go:27 +0x1c0
```

**Comment by thorfour** [comment]
Gonna close this issue as the sorting resolves the original panic. If you're still seeing the different panic you reported @metalmatze please open a separate issue and tag me on it.
