### ISSUE TITLE
panic during query with arrow ingestion enabled

### ISSUE THREAD

**Issue by thorfour** [polarsignals/frostdb#373]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xffa4ae]

goroutine 784596 [running]:
github.com/apache/arrow/go/v10/arrow/array.(*Binary).Value(...)
	github.com/apache/arrow/go/v10@v10.0.1/arrow/array/binary.go:52
github.com/polarsignals/frostdb/query/physicalplan.DictionaryArrayScalarEqual(0xc01bf4bdb0, {0x522b5f0?, 0xc08c8d6458?})
	github.com/polarsignals/frostdb@v0.0.0-20230227172736-d0eea82a3fcb/query/physicalplan/binaryscalarexpr.go:223 +0x22e
github.com/polarsignals/frostdb/query/physicalplan.BinaryScalarOperation({0x5235e60, 0xc01bf4bdb0}, {0x522b5f0?, 0xc08c8d6458?}, 0x1)
	github.com/polarsignals/frostdb@v0.0.0-20230227172736-d0eea82a3fcb/query/physicalplan/binaryscalarexpr.go:140 +0x85e
github.com/polarsignals/frostdb/query/physicalplan.BinaryScalarExpr.Eval({0xc0270f1230?, 0x5235e60?, {0x522b5f0?, 0xc08c8d6458?}}, {0x52321e8, 0xc061a78420})
	github.com/polarsignals/frostdb@v0.0.0-20230227172736-d0eea82a3fcb/query/physicalplan/binaryscalarexpr.go:55 +0x85
github.com/polarsignals/frostdb/query/physicalplan.(*AndExpr).Eval(0xc00d88e740, {0x52321e8, 0xc061a78420})
	github.com/polarsignals/frostdb@v0.0.0-20230227172736-d0eea82a3fcb/query/physicalplan/filter.go:156 +0x37
github.com/polarsignals/frostdb/query/physicalplan.(*AndExpr).Eval(0xc00d88e760, {0x52321e8, 0xc061a78420})
	github.com/polarsignals/frostdb@v0.0.0-20230227172736-d0eea82a3fcb/query/physicalplan/filter.go:161 +0x5e
github.com/polarsignals/frostdb/query/physicalplan.(*AndExpr).Eval(0xc00d88e780, {0x52321e8, 0xc061a78420})
	github.com/polarsignals/frostdb@v0.0.0-20230227172736-d0eea82a3fcb/query/physicalplan/filter.go:161 +0x5e
github.com/polarsignals/frostdb/query/physicalplan.(*AndExpr).Eval(0xc00d88e7a0, {0x52321e8, 0xc061a78420})
	github.com/polarsignals/frostdb@v0.0.0-20230227172736-d0eea82a3fcb/query/physicalplan/filter.go:161 +0x5e
github.com/polarsignals/frostdb/query/physicalplan.(*AndExpr).Eval(0xc00d88e7c0, {0x52321e8, 0xc061a78420})
	github.com/polarsignals/frostdb@v0.0.0-20230227172736-d0eea82a3fcb/query/physicalplan/filter.go:161 +0x5e
github.com/polarsignals/frostdb/query/physicalplan.(*AndExpr).Eval(0xc00d88e7e0, {0x52321e8, 0xc061a78420})
	github.com/polarsignals/frostdb@v0.0.0-20230227172736-d0eea82a3fcb/query/physicalplan/filter.go:161 +0x5e
github.com/polarsignals/frostdb/query/physicalplan.(*AndExpr).Eval(0xc00d88e800, {0x52321e8, 0xc061a78420})
	github.com/polarsignals/frostdb@v0.0.0-20230227172736-d0eea82a3fcb/query/physicalplan/filter.go:161 +0x5e
github.com/polarsignals/frostdb/query/physicalplan.(*AndExpr).Eval(0xc00d88e820, {0x52321e8, 0xc061a78420})
	github.com/polarsignals/frostdb@v0.0.0-20230227172736-d0eea82a3fcb/query/physicalplan/filter.go:161 +0x5e
github.com/polarsignals/frostdb/query/physicalplan.filter({0x520b2e0, 0x7256b40}, {0x5203670?, 0xc00d88e820?}, {0x52321e8, 0xc061a78420?})
	github.com/polarsignals/frostdb@v0.0.0-20230227172736-d0eea82a3fcb/query/physicalplan/filter.go:252 +0x6d
github.com/polarsignals/frostdb/query/physicalplan.(*PredicateFilter).Callback(0xc0270ec580, {0x521b2f8, 0xc0270df860}, {0x52321e8?, 0xc061a78420?})
	github.com/polarsignals/frostdb@v0.0.0-20230227172736-d0eea82a3fcb/query/physicalplan/filter.go:235 +0x7a
github.com/polarsignals/frostdb/query/physicalplan.(*noopOperator).Callback(0x40bc94?, {0x521b2f8?, 0xc0270df860?}, {0x52321e8?, 0xc061a78420?})
	github.com/polarsignals/frostdb@v0.0.0-20230227172736-d0eea82a3fcb/query/physicalplan/physicalplan.go:208 +0x35
github.com/polarsignals/frostdb.(*Table).Iterator.func1()
	github.com/polarsignals/frostdb@v0.0.0-20230227172736-d0eea82a3fcb/table.go:791 +0x234
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
	```

**Comment by thorfour** [comment]
This panic would happen when an array is empty, we have a lot of guards around empty records, so this most commonly happens when there's a reference accounting problem (record has been released).

Anecdotally if I turn off compaction I'm unable to reproduce this panic, which further corroborates the hypothesis that this is an accounting error.

**Comment by thorfour** [comment]
This is actually due to the asynchronous query nature in regards to compaction. We wait to release the records until the new index is swapped out, however we can't know that a query isn't currently active in the old index and wont try and read these records.

**Comment by thorfour** [comment]
So, looking closer at block rotation, we don't actually ever release any of the records in the block, so it can't be causing this panic however it is likely causing a memory bloat. Will open separate ticket to address that.

**Comment by thorfour** [comment]
`pendingBlocks` may be returned by the `memoryBlocks()` function, while at the same time that pending block is being dropped (releasing the arrow records contained in the block)
