### ISSUE TITLE
[arrow ingestion] panic on ingest

### ISSUE THREAD

**Issue by thorfour** [polarsignals/frostdb#414]
```
panic: arrow/array: index out of range

goroutine 6210 [running]:
github.com/apache/arrow/go/v10/arrow/array.(*Binary).Value(...)
	github.com/apache/arrow/go/v10@v10.0.1/arrow/array/binary.go:53
github.com/polarsignals/frostdb/pqarrow.appendToRow({0xc028532000, 0x14, 0x22}, {0x51d8440?, 0xc028499d60?}, 0x132, 0xc000096800?, 0xc02852c480?, 0x0?)
	github.com/polarsignals/frostdb@v0.0.0-20230323200733-2d118da30218/pqarrow/parquet.go:56 +0x12fa
github.com/polarsignals/frostdb/pqarrow.getRecordRow(0x51d4a88?, 0xc?, {0x51d4748, 0xc0284862a0}, 0xc001647140?, {0xc02852c480, 0x22, 0xc0284862d0?}, {0xc001515000, 0x22, ...})
	github.com/polarsignals/frostdb@v0.0.0-20230323200733-2d118da30218/pqarrow/parquet.go:85 +0x15a
github.com/polarsignals/frostdb/pqarrow.RecordToRow(0x5190a20?, 0xc02846f080, {0x51d4748, 0xc0284862a0}, 0xd?)
	github.com/polarsignals/frostdb@v0.0.0-20230323200733-2d118da30218/pqarrow/parquet.go:71 +0xcd
github.com/polarsignals/frostdb/pqarrow.RecordToDynamicRow(0xc0015281c0, {0x51d4748, 0xc0284862a0}, 0x132)
	github.com/polarsignals/frostdb@v0.0.0-20230323200733-2d118da30218/pqarrow/parquet.go:153 +0x111
github.com/polarsignals/frostdb.(*TableBlock).insertRecordToGranules(0xc000ffc000, 0xa, {0x51d4748, 0xc0284862a0})
	github.com/polarsignals/frostdb@v0.0.0-20230323200733-2d118da30218/table.go:1249 +0xa5
github.com/polarsignals/frostdb.(*TableBlock).InsertRecord(0xc000ffc000, {0x51bd8c0?, 0xc0263fed20?}, 0x3f6c762?, {0x51d4748, 0xc0284862a0})
	github.com/polarsignals/frostdb@v0.0.0-20230323200733-2d118da30218/table.go:1062 +0xcb
github.com/polarsignals/frostdb.(*Table).InsertRecord(0xc001404140, {0x51bd8c0, 0xc0263fed20}, {0x51d4748, 0xc0284862a0})
	github.com/polarsignals/frostdb@v0.0.0-20230323200733-2d118da30218/table.go:695 +0x207
github.com/parca-dev/parca/pkg/parcacol.NormalizedIngester.Ingest({{0x518d1a0, 0xc001596f50}, {0x51aeb20, 0xc001404140}, 0xc001662930, 0xc0016cde00, {0xc026d99c80, 0x18, 0x18}, {0x0, ...}, ...}, ...)
	github.com/parca-dev/parca/pkg/parcacol/ingest.go:146 +0x45f
github.com/parca-dev/parca/pkg/parcacol.Ingester.Ingest({{0x518d1a0, 0xc001596f50}, {0x51aeb20, 0xc001404140}, 0xc001662930, {0x51d48e8, 0xc000f90300}, 0xc0016cde00}, {0x51bd8c0, 0xc0263fed20}, ...)
	github.com/parca-dev/parca/pkg/parcacol/ingest.go:206 +0x32e
github.com/parca-dev/parca/pkg/profilestore.(*ProfileColumnStore).writeSeries(0x5?, {0x51bd8c0?, 0xc0263fed20?}, 0x3f758f2?)
	github.com/parca-dev/parca/pkg/profilestore/profilecolumnstore.go:92 +0xd2
github.com/parca-dev/parca/pkg/profilestore.(*ProfileColumnStore).WriteRaw(0xc001691da0, {0x51bd8c0?, 0xc0263fecf0?}, 0xc02446ad20)
	github.com/parca-dev/parca/pkg/profilestore/profilecolumnstore.go:133 +0x12c
github.com/parca-dev/parca/gen/proto/go/parca/profilestore/v1alpha1._ProfileStoreService_WriteRaw_Handler.func1({0x51bd8c0, 0xc0263fecf0}, {0x3d21b80?, 0xc02446ad20})
	github.com/parca-dev/parca/gen/proto/go/parca/profilestore/v1alpha1/profilestore_vtproto.pb.go:100 +0x78
```

This was encountered on `demo.parca.dev` at `51ca8c62`

**Comment by thorfour** [comment]
It seems like the arrow record is being release before being ingested...
