### ISSUE TITLE
pqarrow: index out of range persisting arrow record

### ISSUE THREAD

**Issue by asubiotto** [polarsignals/frostdb#427]
Seeing this in production:
```
panic: runtime error: index out of range [0] with length 0

goroutine 34012 [running]:
github.com/apache/arrow/go/v10/arrow/array.(*simpleRecord).Column(0xc00f8b05b0?, 0xc16aa87998?)
	github.com/apache/arrow/go/v10@v10.0.1/arrow/array/record.go:206 +0x3a
github.com/polarsignals/frostdb/pqarrow.getRecordRow(0xd?, 0xd?, {0x2c10868, 0xc1a46ef200}, 0xa?, {0xc016213a00, 0x10, 0x3?}, {0xc16aef0580, 0x10, ...})
	github.com/polarsignals/frostdb@v0.0.0-20230425155736-e1792af839f6/pqarrow/parquet.go:90 +0x124
github.com/polarsignals/frostdb/pqarrow.RecordToFile(0xc00f8b05b0, 0xc174f78a80, {0x2c10868, 0xc1a46ef200})
	github.com/polarsignals/frostdb@v0.0.0-20230425155736-e1792af839f6/pqarrow/parquet.go:179 +0x2ef
github.com/polarsignals/frostdb/parts.(*Part).SerializeBuffer(0xc00f8b05b0?, 0x2bda260?, 0xc01378f6e0?)
	github.com/polarsignals/frostdb@v0.0.0-20230425155736-e1792af839f6/parts/part.go:53 +0x33
github.com/polarsignals/frostdb/parts.(*Part).AsSerializedBuffer(0xc00996c190, 0xc00f8b05b0)
	github.com/polarsignals/frostdb@v0.0.0-20230425155736-e1792af839f6/parts/part.go:69 +0x10a
github.com/polarsignals/frostdb.(*TableBlock).Serialize.func1.1(0x40?)
	github.com/polarsignals/frostdb@v0.0.0-20230425155736-e1792af839f6/table.go:1468 +0x48
github.com/polarsignals/frostdb.(*Granule).PartsForTx.func1(0xc1f60f3558?)
	github.com/polarsignals/frostdb@v0.0.0-20230425155736-e1792af839f6/granule.go:102 +0x3d
github.com/polarsignals/frostdb/parts.(*List).Iterate(0xc16983b0a0, 0xc0b3b2f9b0)
	github.com/polarsignals/frostdb@v0.0.0-20230425155736-e1792af839f6/parts/part_list.go:90 +0x5f
github.com/polarsignals/frostdb.(*Granule).PartsForTx(0x0?, 0x3000100?, 0x0?)
	github.com/polarsignals/frostdb@v0.0.0-20230425155736-e1792af839f6/granule.go:96 +0x47
github.com/polarsignals/frostdb.(*TableBlock).Serialize.func1({0x2bdf440?, 0xc1bf965200?})
	github.com/polarsignals/frostdb@v0.0.0-20230425155736-e1792af839f6/table.go:1467 +0x85
github.com/google/btree.(*node[...]).iterate(0x2c33480, 0xc00a182ad0, {{0x0?, 0x0?}, 0xff?}, {{0x0?, 0x0?}, 0x5?}, 0x0, 0x1, ...)
	github.com/google/btree@v1.1.2/btree_generic.go:522 +0x3f7
github.com/google/btree.(*node[...]).iterate(0x2c33480, 0xc000c85db0, {{0x0?, 0x0?}, 0xff?}, {{0x0?, 0x0?}, 0x5?}, 0x0, 0x1, ...)
	github.com/google/btree@v1.1.2/btree_generic.go:510 +0x23f
github.com/google/btree.(*node[...]).iterate(0x2c33480, 0xc013a73580, {{0x0?, 0x0?}, 0xff?}, {{0x0?, 0x0?}, 0x5?}, 0x0, 0x1, ...)
	github.com/google/btree@v1.1.2/btree_generic.go:510 +0x23f
github.com/google/btree.(*node[...]).iterate(0x2c33480, 0x0, {{0x0?, 0x0?}, 0x0?}, {{0x0?, 0x0?}, 0x5d?}, 0x0, 0x1, ...)
	github.com/google/btree@v1.1.2/btree_generic.go:510 +0x23f
github.com/google/btree.(*node[...]).iterate(0x2c33480, 0xc1f1decb20, {{0x0?, 0x0?}, 0x7?}, {{0x0?, 0x0?}, 0x80?}, 0x0, 0x0, ...)
	github.com/google/btree@v1.1.2/btree_generic.go:527 +0x4be
github.com/google/btree.(*BTreeG[...]).Ascend(0x416010?, 0xbe4?)
	github.com/google/btree@v1.1.2/btree_generic.go:779 +0x49
github.com/google/btree.(*BTree).Ascend(...)
	github.com/google/btree@v1.1.2/btree_generic.go:1029
github.com/polarsignals/frostdb.(*TableBlock).Serialize(0xc007362900, {0x2be3b00, 0xc03da1ba28})
	github.com/polarsignals/frostdb@v0.0.0-20230425155736-e1792af839f6/table.go:1464 +0x15e
github.com/polarsignals/frostdb.(*TableBlock).Persist.func1()
	github.com/polarsignals/frostdb@v0.0.0-20230425155736-e1792af839f6/store.go:40 +0x6c
created by github.com/polarsignals/frostdb.(*TableBlock).Persist
	github.com/polarsignals/frostdb@v0.0.0-20230425155736-e1792af839f6/store.go:38 +0x2a5
```

**Comment by thorfour** [comment]
Merging into #425
