### ISSUE TITLE
panic while serializing

### ISSUE THREAD

**Issue by thorfour** [polarsignals/frostdb#551]
```
panic: runtime error: index out of range [0] with length 0

goroutine 73688 [running]:
github.com/apache/arrow/go/v14/arrow/array.(*simpleRecord).Column(0x1418878a100?, 0x1401e4224e0?)
	/Users/thor/go/pkg/mod/github.com/apache/arrow/go/v14@v14.0.0-20230829105931-29819425f428/arrow/array/record.go:234 +0x54
github.com/polarsignals/frostdb/pqarrow.getRecordRow(0x140b7ba8fc0?, 0x1403057bc20?, {0x1054388e0, 0x1403057bc20}, 0x141c28075b8?, {0x140c5f4b800, 0x3c, 0x105428eb8?}, {0x1405a8aaa00, 0x3d, ...})
	/Users/thor/go/src/github.com/polarsignals/frostdb/pqarrow/parquet.go:81 +0xe4
github.com/polarsignals/frostdb/pqarrow.RecordToFile(0x1418878a100, 0x14063953920, {0x1054388e0, 0x1403057bc20})
	/Users/thor/go/src/github.com/polarsignals/frostdb/pqarrow/parquet.go:142 +0x21c
github.com/polarsignals/frostdb/parts.(*Part).SerializeBuffer(0x1418878a100?, 0x105428578?, 0x140b7ba8e10?)
	/Users/thor/go/src/github.com/polarsignals/frostdb/parts/part.go:54 +0x34
github.com/polarsignals/frostdb/parts.(*Part).AsSerializedBuffer(0x1409a1560a0, 0x1418878a100)
	/Users/thor/go/src/github.com/polarsignals/frostdb/parts/part.go:70 +0xbc
github.com/polarsignals/frostdb.compactLevel0IntoLevel1(0x14057a1b950, 0x140e78bfb80?, {0x1403e026800, 0x399, 0x500}, {0x0, 0x0, 0x1?}, 0x3ff0000000000000, 0x140e78bfa58)
	/Users/thor/go/src/github.com/polarsignals/frostdb/compaction.go:593 +0x3e0
github.com/polarsignals/frostdb.(*TableBlock).Serialize.func2({0x1054285b8?, 0x14003fd9c80?})
	/Users/thor/go/src/github.com/polarsignals/frostdb/table.go:1172 +0x1b8
github.com/google/btree.(*node).iterate(0x140033454c0, 0x105428538?, {0x0, 0x0}, {0x0, 0x0}, 0x0, 0x0, 0x140d9dc7d70)
	/Users/thor/go/pkg/mod/github.com/google/btree@v1.0.1/btree.go:524 +0x288
github.com/google/btree.(*BTree).Ascend(...)
	/Users/thor/go/pkg/mod/github.com/google/btree@v1.0.1/btree.go:777
github.com/polarsignals/frostdb.(*TableBlock).Serialize(0x14057a1b950, {0x105428a38, 0x105b5a400})
	/Users/thor/go/src/github.com/polarsignals/frostdb/table.go:1160 +0x2cc
github.com/polarsignals/frostdb.Benchmark_Serialize_External(0x14000fa4f00)
	/Users/thor/go/src/github.com/polarsignals/frostdb/bench_test.go:486 +0x18c
testing.(*B).runN(0x14000fa4f00, 0x1)
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/testing/benchmark.go:193 +0x128
testing.(*B).run1.func1()
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/testing/benchmark.go:233 +0x50
created by testing.(*B).run1 in goroutine 1
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/testing/benchmark.go:226 +0x90
exit status 2
FAIL	github.com/polarsignals/frostdb	1687.615s
FAIL
```

**Comment by brancz** [comment]
This could be related to the thing we’ve seen in Parca where if a binary array that only contains one item, the empty item, and read that item you `nil` in Go. Now if you add that “first” item to a binary builder it will actually be interpreted as nil and it will append a null item instead of the empty item.

**Comment by thorfour** [comment]
> This could be related to the thing we’ve seen in Parca where if a binary array that only contains one item, the empty item, and read that item you `nil` in Go. Now if you add that “first” item to a binary builder it will actually be interpreted as nil and it will append a null item instead of the empty item.

Could be, but this happened inconsistently which to mean indicates that this is a race condition with releasing records somehow

**Comment by thorfour** [comment]
This was fixed with the latest parquet-go fixes
